// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAldoVAVZo_Y0kLHckFFPzXGMQo1_ceKZg',
    appId: '1:169312288908:web:e249f0755c20f252e03ba9',
    messagingSenderId: '169312288908',
    projectId: 'firebasedemo-456123',
    authDomain: 'fir-demo-456123.firebaseapp.com',
    databaseURL: 'https://firebasedemo-456123-default-rtdb.firebaseio.com',
    storageBucket: 'firebasedemo-456123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRr7Pl82BHwplZLDbkZf0Orgy_C5Ds7v8',
    appId: '1:169312288908:android:ff232311e7a6c4a5e03ba9',
    messagingSenderId: '169312288908',
    projectId: 'firebasedemo-456123',
    databaseURL: 'https://firebasedemo-456123-default-rtdb.firebaseio.com',
    storageBucket: 'firebasedemo-456123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtQ_YO9qcQ1sIYjkUSs1_Baa3NxShftNI',
    appId: '1:169312288908:ios:40986f84d6dcb948e03ba9',
    messagingSenderId: '169312288908',
    projectId: 'firebasedemo-456123',
    databaseURL: 'https://firebasedemo-456123-default-rtdb.firebaseio.com',
    storageBucket: 'firebasedemo-456123.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtQ_YO9qcQ1sIYjkUSs1_Baa3NxShftNI',
    appId: '1:169312288908:ios:40986f84d6dcb948e03ba9',
    messagingSenderId: '169312288908',
    projectId: 'firebasedemo-456123',
    databaseURL: 'https://firebasedemo-456123-default-rtdb.firebaseio.com',
    storageBucket: 'firebasedemo-456123.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAldoVAVZo_Y0kLHckFFPzXGMQo1_ceKZg',
    appId: '1:169312288908:web:4f2b51b5b6669faae03ba9',
    messagingSenderId: '169312288908',
    projectId: 'firebasedemo-456123',
    authDomain: 'fir-demo-456123.firebaseapp.com',
    databaseURL: 'https://firebasedemo-456123-default-rtdb.firebaseio.com',
    storageBucket: 'firebasedemo-456123.appspot.com',
  );
}
